### ISSUE TITLE
Support running under a sub-path

### ISSUE THREAD

**Issue by jaredsmith** [nimbleape/dana-the-stream-gatekeeper#20]
Dana assumes that it's running at the root of the web server (https://example.com/) and doesn't support running under a sub-path (https://example.com/dana/ or https://example.com/something/dana/) for example.

**Comment by gtjoseph** [comment]
You can do it manually but it'd be nice if "yarn build " could do it with an option.

You just need to make 2 changes...
In package.json, add `"homepage": "/dana",`
In src/components/Routes.js, change `<Router>` to `<Router basename="/dana">`

**Comment by gtjoseph** [comment]
You can now...
`$ npm_package_homepage=/dana yarn build:prefix`
